<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>lapse</AssemblyName>
    <RootNamespace>Lapse.Cli</RootNamespace>
    <PublishAot>true</PublishAot>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lapse.Infrastructure\Lapse.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\lapse.example.json" LogicalName="Lapse.lapse.example.json" />
  </ItemGroup>
</Project>
